# base image 
# FROM alpine  # contain very small dependencies 
    # solution 1. first base image 
              #2. try to install node on alpine  
              
              # *. why alphine it's a smallest version of docker [ nothing install hear ]
FROM node:alpine  


        # why error because docker is a snapshot or small space of hard drive 
        # it's didnt know about the packege json and index json file 
        # first we have to garanteed about it's in out snapshot 
        # so we have to copy our file in  to  the container 



# container command 
WORKDIR /usr/app
COPY ./package.json ./
RUN npm install 
COPY ./ ./     

        # what we do ?? this is a simple speed up process 
        # becue prevous comming all the package and index js copy usign one command [  copy ./ ./ ]
        # if you change the source code [index.js] , docker chace memeory show there is a change in prevous step [copy ./ ./] 
        # that means it's run again and install all the dependencies again 
        # best thing to do device sourse code and package dependencies in to do [first package  then after copyt all the directory like show in command]




# container run command 
CMD ["npm","start"]