# user an existing docker image as a base 
FROM alpine 

# download and install a dependency 
RUN apk add --update redis 

# tell the image what to do when it start 
# as a contgainer 
CMD ["redis-server"]